name: app_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  in_app_purchase: ^3.2.0
  provider: ^6.1.2
  purchases_flutter: ^8.1.4
  purchases_ui_flutter: ^8.1.4
  sign_in_with_apple: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
